<a href="https://colab.research.google.com/github/MasterDohko/-Curso-de-Fundamentos-de-Estad-stica-y-An-lisis-de-Datos-con-Python/blob/master/Conceptos_Probabilidad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from datetime import date


#####Lanzamiento de una moneda

In [9]:
universo = ['cara','sello']
p_cara= 1/2

Libreria **scipy.stats** importamos experimento **bernoulli**

 **Caras de una moneda**

 Como la funcion bernoulli puede traer unicamente 1 o 0

In [5]:
from scipy.stats import bernoulli
bernoulli.rvs(p=p_cara)

0

In [12]:
universo[bernoulli.rvs(p=p_cara)]

'cara'

In [15]:
bernoulli.rvs(p=p_cara, size=19)

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

##DISTRIBUCION BINOMIAL

Suma de n eventos independientes de Bernoulli

In [16]:
sum(bernoulli.rvs(p=p_cara, size=19))

10

##DISTRIBUCION DE PROBABILIDAD

Algunos valores tienes mas probabilidad de efectuarse que otros dentro de la distribucion

In [21]:
from scipy.stats import binom
#Con el parametro size repetimes la cantidad de veces que deseamos el experimento
binom.rvs(p=p_cara, n = 19, size=100)

array([ 6,  8,  7,  9,  7, 13, 14, 13, 13, 10,  9,  9, 10,  7, 10,  8, 10,
       11,  7,  9, 10,  9, 10, 11,  9, 10, 13,  7, 12,  7,  8, 12,  6, 13,
        8,  9,  8, 10, 10,  7,  9,  8, 10, 11,  8, 11,  9, 11,  6,  8, 10,
        9, 11,  9, 11,  9,  9, 12, 11, 13,  7,  5, 11,  4,  9, 10,  8,  7,
       12, 14,  9,  7, 12, 10,  8,  9, 11,  9,  9, 14, 11,  6,  8,  9, 11,
        9, 10,  9,  9,  9, 10,  8, 10, 13, 11, 10,  6,  8, 10,  7])

##Frecuencia

In [24]:
#Ver cuantas veces aparecen esos valores en la lista, con que frecuencia
import pandas as pd
pd.Series(binom.rvs(p=p_cara, n = 19, size=100)).value_counts()/100

9     0.21
10    0.20
11    0.11
8     0.11
12    0.10
6     0.09
7     0.06
13    0.05
5     0.04
16    0.01
15    0.01
14    0.01
dtype: float64

## Medidas de tendencia central

Media o promedio geometrico y aritmetico

Mediana

Moda


In [27]:
import numpy as np
import pandas as pd
import scipy
import scipy.stats

Importar archivo y listar las columnas de dataframe

In [25]:
from google.colab import files
uploaded = files.upload()

Saving bicicletas-compartidas.csv to bicicletas-compartidas.csv


In [28]:
df = pd.read_csv('bicicletas-compartidas.csv')
df.columns

Index(['fecha', 'bicis-compartidas', 'temp-obs', 'sens-temp', 'hum', 'viento',
       'codigo-clima', 'festivo', 'findesemana', 'cuartil-ano'],
      dtype='object')

In [29]:
y = df['bicis-compartidas'].values
y

array([182, 138, 134, ..., 337, 224, 139])

In [ ]:
# Limpiar 0 y reemplazarlos por 1
y = np.where(y == 0, 1, y)
print(y)

##**Medidas**

Se pueden obtener con NumPi o con Pandas, al final debe ser el mismo resultado, en la primera linea se ve la ejecución con NumPi, para algunos ejemplos como el mínimo el valor para pandas varia pues en el Dataframe no se hizo la limpieza de 0


Minimo

In [30]:
np.min(y)

0

Maximo

In [31]:
np.max(y)

7860

***Promedio:*** sum(yi)/n

In [48]:
np.mean(y)

1143.1016423567244

In [37]:
np.sum(y)/len(y)

1143.1016423567244

Mediana

In [39]:
np.median(y)

844.0

####Moda

valor de y con la maxima frecuencia

In [43]:
moda = np.nan

valores, conteo_valores = np.unique(y, return_counts = True)
pos = np.argmax(conteo_valores)
moda = valores[pos]
moda

46

####DESVIACION ESTANDAR

In [44]:
np.std(y)

1085.0769112908038

***Revisiones de los valores***

In [52]:
y_alterado = y.copy()
y_alterado [y_alterado == max(y_alterado)] = 1000000000000000000

media

In [55]:
print(np.mean(y))
print(np.mean(y_alterado))

1143.1016423567244
57425060297455.97


mediana

In [57]:
print(np.median(y))
print(np.median(y_alterado))

844.0
844.0
